import {
  Activity,
  Baby,
  Banknote,
  Beer,
  Bike,
  Book,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Bus,
  Calculator,
  Calendar,
  Camera,
  Car,
  Cat,
  CircleParking,
  Clapperboard,
  Clock,
  Coffee,
  Coins,
  CreditCard,
  CupSoda,
  Dog,
  DollarSign,
  Droplet,
  Droplets,
  Dumbbell,
  FileText,
  Film,
  Fuel,
  Gamepad2,
  Gift,
  Globe,
  GraduationCap,
  Hammer,
  HandCoins,
  Handbag,
  Headphones,
  Heart,
  HeartPulse,
  Home,
  Hospital,
  HousePlug,
  Key,
  Landmark,
  Laptop,
  Lightbulb,
  Lock,
  Luggage,
  MapPin,
  Monitor,
  Mountain,
  Music,
  Notebook,
  Package,
  Paintbrush,
  Palette,
  ParkingMeter,
  PawPrint,
  Percent,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  PlugZap,
  Receipt,
  School,
  Scissors,
  Shield,
  Ship,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  Sun,
  Tag,
  Tags,
  Tent,
  ThermometerSun,
  Ticket,
  Toolbox,
  TrainFront,
  TrendingDown,
  TrendingUp,
  Truck,
  Tv,
  Umbrella,
  User,
  Users,
  Utensils,
  UtensilsCrossed,
  Vault,
  Wallet,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from 'lucide-react-native';

export const CATEGORY_ICONS = {
  'shopping-cart': ShoppingCart,
  'shopping-bag': ShoppingBag,
  'shopping-basket': ShoppingBasket,
  tag: Tag,
  tags: Tags,
  package: Package,
  gift: Gift,
  handbag: Handbag,
  coffee: Coffee,
  utensils: Utensils,
  'utensils-crossed': UtensilsCrossed,
  pizza: Pizza,
  wine: Wine,
  beer: Beer,
  'cup-soda': CupSoda,
  car: Car,
  bus: Bus,
  'train-front': TrainFront,
  bike: Bike,
  fuel: Fuel,
  plane: Plane,
  ship: Ship,
  truck: Truck,
  'parking-meter': ParkingMeter,
  'circle-parking': CircleParking,
  home: Home,
  lightbulb: Lightbulb,
  'plug-zap': PlugZap,
  zap: Zap,
  droplet: Droplet,
  droplets: Droplets,
  wifi: Wifi,
  'thermometer-sun': ThermometerSun,
  'house-plug': HousePlug,
  'heart-pulse': HeartPulse,
  stethoscope: Stethoscope,
  pill: Pill,
  hospital: Hospital,
  activity: Activity,
  dumbbell: Dumbbell,
  heart: Heart,
  wallet: Wallet,
  'credit-card': CreditCard,
  banknote: Banknote,
  coins: Coins,
  'hand-coins': HandCoins,
  receipt: Receipt,
  percent: Percent,
  calculator: Calculator,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'piggy-bank': PiggyBank,
  landmark: Landmark,
  vault: Vault,
  'dollar-sign': DollarSign,
  film: Film,
  clapperboard: Clapperboard,
  tv: Tv,
  'gamepad-2': Gamepad2,
  headphones: Headphones,
  music: Music,
  ticket: Ticket,
  'book-open': BookOpen,
  'graduation-cap': GraduationCap,
  school: School,
  book: Book,
  notebook: Notebook,
  baby: Baby,
  users: Users,
  user: User,
  dog: Dog,
  cat: Cat,
  'paw-print': PawPrint,
  luggage: Luggage,
  tent: Tent,
  mountain: Mountain,
  umbrella: Umbrella,
  'map-pin': MapPin,
  globe: Globe,
  scissors: Scissors,
  palette: Palette,
  paintbrush: Paintbrush,
  briefcase: Briefcase,
  'briefcase-business': BriefcaseBusiness,
  building: Building,
  'building-2': Building2,
  wrench: Wrench,
  hammer: Hammer,
  toolbox: Toolbox,
  smartphone: Smartphone,
  laptop: Laptop,
  monitor: Monitor,
  camera: Camera,
  shield: Shield,
  lock: Lock,
  key: Key,
  calendar: Calendar,
  clock: Clock,
  sun: Sun,
  star: Star,
  'file-text': FileText,
} as const;

export type CategoryIconKey = keyof typeof CATEGORY_ICONS;

export const CATEGORY_COLOR_PRESETS: { color: string; bgColor: string }[] = [
  { color: '#2f9e6f', bgColor: '#e3f4ec' },
  { color: '#e08a2b', bgColor: '#fbf0df' },
  { color: '#3b7fd4', bgColor: '#e6effb' },
  { color: '#9b6dd6', bgColor: '#f0e9fb' },
  { color: '#d95a6a', bgColor: '#fbe7ea' },
  { color: '#2f6bed', bgColor: '#e8effe' },
  { color: '#1f9d68', bgColor: '#e3f4ec' },
  { color: '#c2884a', bgColor: '#f5ebe0' },
];

export const DEFAULT_CATEGORIES: {
  name: string;
  kind: 'income' | 'expense';
  color: string;
  bgColor: string;
  icon: CategoryIconKey;
  sortOrder: number;
}[] = [
  {
    name: 'Groceries',
    kind: 'expense',
    color: '#2f9e6f',
    bgColor: '#e3f4ec',
    icon: 'shopping-cart',
    sortOrder: 0,
  },
  {
    name: 'Dining',
    kind: 'expense',
    color: '#e08a2b',
    bgColor: '#fbf0df',
    icon: 'coffee',
    sortOrder: 1,
  },
  {
    name: 'Transport',
    kind: 'expense',
    color: '#3b7fd4',
    bgColor: '#e6effb',
    icon: 'car',
    sortOrder: 2,
  },
  {
    name: 'Shopping',
    kind: 'expense',
    color: '#9b6dd6',
    bgColor: '#f0e9fb',
    icon: 'shopping-bag',
    sortOrder: 3,
  },
  {
    name: 'Bills',
    kind: 'expense',
    color: '#d95a6a',
    bgColor: '#fbe7ea',
    icon: 'file-text',
    sortOrder: 4,
  },
  {
    name: 'Health',
    kind: 'expense',
    color: '#2f6bed',
    bgColor: '#e8effe',
    icon: 'heart-pulse',
    sortOrder: 5,
  },
  {
    name: 'Salary',
    kind: 'income',
    color: '#1f9d68',
    bgColor: '#e3f4ec',
    icon: 'trending-up',
    sortOrder: 6,
  },
];
